---
title: Missions
---



This page will house information for current and past glider missions. 

To date we have conducted several glider missions in collaboration with Oregon State University and SWFSC. Deployments that are part of the PAM-SI can be found here: [nmfs-ost/PAM-Glider Deployment Tracker](https://stunning-adventure-z2nw12l.pages.github.io/missions.html#pifsc-seaglider-mission-tracker)


### PIFSC Seaglider Mission Tracker

The below table will list basic information and links to reports and data for all in progress and past missions. See [below](#data-links) for details on data links and availability. 

<!-- <iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vT-sYW-fETyx-6HpviyS7uU6wE8XhtSEpcCebbD66hkxxJ20HeFADeLBNzKIik46XsPskSGKFENOYQz/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false" style="width:600px; height:400px; border:2px solid #1EBEC7;"></iframe> -->

[Spreadsheet to track current and completed missions](https://docs.google.com/spreadsheets/d/1cuMfl72pcrMxzPEMjluCLirsLtIb8wKwBYsVkrQ-fkU/edit?usp=sharing)(NOAA only)

| Year | Project | Mission | Location | Sensors | Report | Piloting Site | ERDDAP | Internal Data |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| 2026 | WHICEAS | sg274_20260128_WHICEAS | Main Hawaiian Islands | CTD, WISPR | coming | [seaglider.pub](https://noaaosu.seaglider.pub/274?mission=20260128_WHICEAS) | NA | coming |
| 2026 | WHICEAS | sg607_20260128_WHICEAS | Main Hawaiian Islands | CTD, WISPR | coming | [seaglider.pub](https://noaaosu.seaglider.pub/607?mission=20260128_WHICEAS) | NA | coming |
| 2026 | WHICEAS | sg639_20260211_WHICEAS | Main Hawaiian Islands | CTD, WISPR | coming | [seaglider.pub](https://noaaosu.seaglider.pub/639?mission=20260211_WHICEAS) | NA | coming |
| 2026 | WHICEAS | sg679_20260205_WHICEAS | Main Hawaiian Islands | CTD, WISPR | coming | [seaglider.pub](https://noaaosu.seaglider.pub/679?mission=20260205_WHICEAS) | NA | coming |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| 2026 | Oahu Sea Trial | sg273_20260107_Oahu | Oahu west side | CTD, WISPR | [link](https://docs.google.com/document/d/1UffCABsUHyub2RHxuZsZbaRiLWyZczTVpiHds5p5_Bg/edit?usp=sharing) | [seaglider.pub](https://noaaosu.seaglider.pub/273?mission=20260107_Oahu) | NA | [pifsc-1 GCP](https://console.cloud.google.com/storage/browser/pifsc-1/glider;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&invt=Abtsgw&project=ggn-nmfs-pamdata-prod-1&prefix=&forceOnObjectsSortingFiltering=false) |
| 2026 | Oahu Sea Trial | sg274_20260107_Oahu | Oahu west side| CTD, WISPR | [link](https://docs.google.com/document/d/1UffCABsUHyub2RHxuZsZbaRiLWyZczTVpiHds5p5_Bg/edit?usp=sharing) | [seaglider.pub](https://noaaosu.seaglider.pub/274?mission=20260107_Oahu) | NA | [pifsc-1 GCP](https://console.cloud.google.com/storage/browser/pifsc-1/glider;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&invt=Abtsgw&project=ggn-nmfs-pamdata-prod-1&prefix=&forceOnObjectsSortingFiltering=false) |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| 2023 | UxS-MHI | sg639_MHI_Apr2023 | Main Hawaiian Islands | CTD, PMARXL (PAM) | [link](https://docs.google.com/document/d/1cFDclB_Pkq1ChZo6NzuxhfPS135sYmd-Jm3CAc6qXVc/edit?tab=t.0) | [OSU basestation](https://gliderfs.coas.oregonstate.edu/sgliderweb/seagliders/sg639/2023-04-11_deployment/procdata/index_archive.php) | NA | [pifsc-1 GCP](https://console.cloud.google.com/storage/browser/pifsc-1/glider/sg639_MHI_Apr2023?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&invt=Abtsgw&project=ggn-nmfs-pamdata-prod-1)|
| 2023 | UxS-MHI | sg679_MHI_May2023 | Main Hawaiian Islands | CTD, WISPR (PAM with near-real-time sperm whale detector) | [link](https://docs.google.com/document/d/1cFDclB_Pkq1ChZo6NzuxhfPS135sYmd-Jm3CAc6qXVc/edit?tab=t.0) | [OSU basestation](https://gliderfs.coas.oregonstate.edu/sgliderweb/seagliders/sg679/2023-05-06_deployment/procdata/index_archive.php) | NA | [pifsc-1 GCP](https://console.cloud.google.com/storage/browser/pifsc-1/glider/sg679_MHI_May2023?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&invt=Abtsgw&project=ggn-nmfs-pamdata-prod-1) |
| 2022 | UxS-MHI | sg639_MHI_Apr2022 | Main Hawaiian Islands | CTD, PMARXL (PAM) | [link](https://docs.google.com/document/d/1cFDclB_Pkq1ChZo6NzuxhfPS135sYmd-Jm3CAc6qXVc/edit?tab=t.0) | [OSU basestation](https://gliderfs.coas.oregonstate.edu/sgliderweb/seagliders/sg639/2022-04-05_deployment/procdata/index_archive.php) | NA | [pifsc-1 GCP](https://console.cloud.google.com/storage/browser/pifsc-1/glider/sg639_MHI_Apr2022?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&invt=Abtsgw&project=ggn-nmfs-pamdata-prod-1) |
| 2022 | UxS-MHI | sg680_MHI_Apr2022 | Main Hawaiian Islands | CTD, PMARXL (PAM) | [link](report_link) | [OSU basestation](https://gliderfs.coas.oregonstate.edu/sgliderweb/seagliders/sg680/2022-04-06_deployment/procdata/index_archive.php) | NA | [pifsc-1 GCP](https://console.cloud.google.com/storage/browser/pifsc-1/glider/sg680_MHI_Apr2022?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&invt=Abtsgw&project=ggn-nmfs-pamdata-prod-1) |
|...|...|...|...|...|...|...|...|...|
_\*Early missions using gliders SG639, SG679, and SG680 were conducted in collaboration with the Cooperative Institute for Marine Ecosystem and Resources Studies, Oregon State University._


### Data Links

The above table contains several links to different data products.

The 'seaglider.pub' column will contain the link the mission piloting/basestation outputs on the public-facing seaglider.pub vis. Missions conducted in collaboration with OSU will be found at [noaaosu.seaglider.pub](https://noaaosu.seaglider.pub). Future PIFSC-owned glider missions will be at pifsc.seaglider.pub (*not yet live*). 

<!-- All missions can be found at [pifsc.seaglider.pub](https://pifsc.seaglider.pub)(link not yet set up). -->

The 'ERDDAP' column will contain the link to the glider dataset when it is published to the [ERDDAP](https://gliders.ioos.us/erddap/index.html) of the [IOOS National Glider Data Assembly Center](https://gliders.ioos.us/).

The 'Internal Data' column contains links to various PIFSC-internal data products, stored within the NMFS PAM-SI Google Cloud Platform (GCP) project. Users will only be able to access these data if they have been granted appropriate access and permissions for that project. There are two types of Internal Data links:

- **piloting**: Raw piloting basestation files, tracks, and data products from the [mission post-processing](data-processing.qmd#mission-post-processing) workflow. The most relevant data products for users will likely be in the 'profiles' folder, specificially the 'gpsSurface' and 'CTD' tables
- **recordings**: Raw and/or processed acoustic data, typically in `.wav` or `.flac` format. May contain decimated datasets (e.g., 1 and 10 kHz sample rate) depending on mission analysis goals

Additional detail on the GCP folder structure can be found in the [PIFSC Glider Lab Data Management Plan](https://docs.google.com/document/d/1FCwBSUFHXaw8124u0K0YmNmUrCakKbkyKyzvz7sumNM/edit?tab=t.0#heading=h.bphdsu7lbiaf)(NOAA only).
